name = "InverseValueProblem"
uuid = "9119f69d-0e20-4b89-8de1-208ce7235821"
authors = ["jzazo <v-javierzazo@microsoft.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
